<?php

namespace Sewik\Domain;

class Filter
{
    const ACCIDENTS_PLACEHOLDER = '%zdarzenie_filter%';
    const VEHICLES_PLACEHOLDER = '%pojazdy_filter%';
    const PARTICIPANTS_PLACEHOLDER = '%uczestnicy_filter%';

    const COLUMN_VOIVODESHIP = 'woj';
    const COLUMN_LOCALITY = 'miejscowosc';
    const COLUMN_DATE = 'data_zdarz';
    const COLUMN_STREET = 'ulica_adres';

    const COLUMNS = [
        self::COLUMN_VOIVODESHIP,
        self::COLUMN_LOCALITY,
        self::COLUMN_DATE,
        self::COLUMN_STREET,
    ];
    const VOIVODESHIP_DOLNOŚLĄSKIE = 'WOJ. DOLNOŚLĄSKIE';
    const VOIVODESHIP_KUJAWSKO_POMORSKIE = 'WOJ. KUJAWSKO-POMORSKIE';
    const VOIVODESHIP_LUBELSKIE = 'WOJ. LUBELSKIE';
    const VOIVODESHIP_LUBUSKIE = 'WOJ. LUBUSKIE';
    const VOIVODESHIP_MAZOWIECKIE = 'WOJ. MAZOWIECKIE';
    const VOIVODESHIP_MAŁOPOLSKIE = 'WOJ. MAŁOPOLSKIE';
    const VOIVODESHIP_OPOLSKIE = 'WOJ. OPOLSKIE';
    const VOIVODESHIP_PODKARPACKIE = 'WOJ. PODKARPACKIE';
    const VOIVODESHIP_PODLASKIE = 'WOJ. PODLASKIE';
    const VOIVODESHIP_POMORSKIE = 'WOJ. POMORSKIE';
    const VOIVODESHIP_WARMIŃSKO_MAZURSKIE = 'WOJ. WARMIŃSKO-MAZURSKIE';
    const VOIVODESHIP_WIELKOPOLSKIE = 'WOJ. WIELKOPOLSKIE';
    const VOIVODESHIP_ZACHODNIOPOMORSKIE = 'WOJ. ZACHODNIOPOMORSKIE';
    const VOIVODESHIP_ŁÓDZKIE = 'WOJ. ŁÓDZKIE';
    const VOIVODESHIP_ŚLĄSKIE = 'WOJ. ŚLĄSKIE';

    const VOIVODESHIP_ŚWIĘTOKRZYSKIE = 'WOJ. ŚWIĘTOKRZYSKIE';
    const VOIVODESHIPS = [
        'Dolnośląskie' => self::VOIVODESHIP_DOLNOŚLĄSKIE,
        'Kujawsko-Pomorskie' => self::VOIVODESHIP_KUJAWSKO_POMORSKIE,
        'Lubelskie' => self::VOIVODESHIP_LUBELSKIE,
        'Lubuskie' => self::VOIVODESHIP_LUBUSKIE,
        'Mazowieckie' => self::VOIVODESHIP_MAZOWIECKIE,
        'Małopolskie' => self::VOIVODESHIP_MAŁOPOLSKIE,
        'Opolskie' => self::VOIVODESHIP_OPOLSKIE,
        'Podkarpackie' => self::VOIVODESHIP_PODKARPACKIE,
        'Podlaskie' => self::VOIVODESHIP_PODLASKIE,
        'Pomorskie' => self::VOIVODESHIP_POMORSKIE,
        'Warmińsko-Mazurskie' => self::VOIVODESHIP_WARMIŃSKO_MAZURSKIE,
        'Wielkopolskie' => self::VOIVODESHIP_WIELKOPOLSKIE,
        'Zachodniopomorskie' => self::VOIVODESHIP_ZACHODNIOPOMORSKIE,
        'Łódzkie' => self::VOIVODESHIP_ŁÓDZKIE,
        'Śląskie' => self::VOIVODESHIP_ŚLĄSKIE,
        'Świętokrzyskie' => self::VOIVODESHIP_ŚWIĘTOKRZYSKIE,
    ];

    const PARTICIPANT_INJURY_SERIOUS = 'RC';
    const PARTICIPANT_INJURY_MINOR = 'RL';
    const PARTICIPANT_INJURY_DEATH = 'ZM';

    const PARTICIPANT_INJURIES = [
        'Ciężko ranny' => self::PARTICIPANT_INJURY_SERIOUS,
        'Lekko ranny' => self::PARTICIPANT_INJURY_MINOR,
        'Śmierć' => self::PARTICIPANT_INJURY_DEATH,
    ];

    const VEHICLE_TYPE_BICYCLE = 'IS01'; //Rower
    const VEHICLE_TYPE_MOPED = 'IS02'; //Motorower
    const VEHICLE_TYPE_MOTORBIKE = 'IS03'; //Motocykl
    const VEHICLE_TYPE_CAR = 'IS04'; //Samochód osobowy z przyczepą
    const VEHICLE_TYPE_TAXI = 'IS06'; //Samochód osobowy TAXI
    const VEHICLE_TYPE_BUS = 'IS07'; //Autobus komunikacji publicznej
    const VEHICLE_TYPE_TRUCK = 'IS09'; //Samochód ciężarowy
    const VEHICLE_TYPE_TRACTOR = 'IS12'; //Ciągnik rolniczy
    const VEHICLE_TYPE_SLOW_MOVING = 'IS14'; //Pojazd wolnobieżny
    const VEHICLE_TYPE_CART = 'IS17'; //Pojazd zaprzęgowy
    const VEHICLE_TYPE_TRAIN = 'IS18'; //Pociąg
    const VEHICLE_TYPE_EMERGENCY = 'IS19'; //Pojazd uprzywilejowany
    const VEHICLE_TYPE_OTHER = 'IS20'; //Inny pojazd
    const VEHICLE_TYPE_TRAM_TROLLEY = 'IS23'; //Tramwaj, trolejbus
    const VEHICLE_TYPE_UNKNOWN = 'IS25'; //Nieustalony
    const VEHICLE_TYPE_QUAD = 'IS29'; //Czterokołowiec lekki (od 11.2015)

    const VEHICLE_TYPES = [
        'Rower' => self::VEHICLE_TYPE_BICYCLE,
        'Skuter' => self::VEHICLE_TYPE_MOPED,
        'Motocykl' => self::VEHICLE_TYPE_MOTORBIKE,
        'Quad' => self::VEHICLE_TYPE_QUAD,
        'Samochód osobowy' => self::VEHICLE_TYPE_CAR,
        'Taksówka' => self::VEHICLE_TYPE_TAXI,
        'Ciężarówka' => self::VEHICLE_TYPE_TRUCK,
        'Autobus' => self::VEHICLE_TYPE_BUS,
        'Tramwaj, trolejbus' => self::VEHICLE_TYPE_TRAM_TROLLEY,
        'Traktor' => self::VEHICLE_TYPE_TRACTOR,
        'Pojazd wolnobieżny' => self::VEHICLE_TYPE_SLOW_MOVING,
        'Zaprzęg' => self::VEHICLE_TYPE_CART,
        'Pociąg' => self::VEHICLE_TYPE_TRAIN,
        'Pojazd uprzewilejowany' => self::VEHICLE_TYPE_EMERGENCY,
        'Inny' => self::VEHICLE_TYPE_OTHER,
        'Nieznany' => self::VEHICLE_TYPE_UNKNOWN,
    ];

    const COUNTIES = [
        'POWIAT ALEKSANDROWSKI',
        'POWIAT AUGUSTOWSKI',
        'POWIAT BARTOSZYCKI',
        'POWIAT BEŁCHATOWSKI',
        'POWIAT BĘDZIŃSKI',
        'POWIAT BIALSKI',
        'POWIAT BIAŁA PODLASKA',
        'POWIAT BIAŁOBRZESKI',
        'POWIAT BIAŁOGARDZKI',
        'POWIAT BIAŁOSTOCKI',
        'POWIAT BIAŁYSTOK',
        'POWIAT BIELSKI',
        'POWIAT BIELSKO-BIAŁA',
        'POWIAT BIERUŃSKO-LĘDZIŃSKI',
        'POWIAT BIESZCZADZKI',
        'POWIAT BIŁGORAJSKI',
        'POWIAT BOCHEŃSKI',
        'POWIAT BOLESŁAWIECKI',
        'POWIAT BRANIEWSKI',
        'POWIAT BRODNICKI',
        'POWIAT BRZESKI',
        'POWIAT BRZEZINY',
        'POWIAT BRZEZIŃSKI',
        'POWIAT BRZOZOWSKI',
        'POWIAT BUSKI',
        'POWIAT BYDGOSKI',
        'POWIAT BYDGOSZCZ',
        'POWIAT BYTOM',
        'POWIAT BYTOWSKI',
        'POWIAT CHEŁM',
        'POWIAT CHEŁMIŃSKI',
        'POWIAT CHEŁMSKI',
        'POWIAT CHODZIESKI',
        'POWIAT CHOJNICKI',
        'POWIAT CHORZÓW',
        'POWIAT CHOSZCZEŃSKI',
        'POWIAT CHRZANOWSKI',
        'POWIAT CIECHANOWSKI',
        'POWIAT CIESZYŃSKI',
        'POWIAT CZARNKOWSKO-TRZCIANECKI',
        'POWIAT CZĘSTOCHOWA',
        'POWIAT CZĘSTOCHOWSKI',
        'POWIAT CZŁUCHOWSKI',
        'POWIAT DĄBROWA GÓRNICZA',
        'POWIAT DĄBROWSKI',
        'POWIAT DĘBICKI',
        'POWIAT DRAWSKI',
        'POWIAT DZIAŁDOWSKI',
        'POWIAT DZIERŻONIOWSKI',
        'POWIAT ELBLĄG',
        'POWIAT ELBLĄSKI',
        'POWIAT EŁCKI',
        'POWIAT GARWOLIŃSKI',
        'POWIAT GDAŃSK',
        'POWIAT GDAŃSKI',
        'POWIAT GDYNIA',
        'POWIAT GIŻYCKI',
        'POWIAT GLIWICE',
        'POWIAT GLIWICKI',
        'POWIAT GŁOGOWSKI',
        'POWIAT GŁUBCZYCKI',
        'POWIAT GNIEŹNIEŃSKI',
        'POWIAT GOLENIOWSKI',
        'POWIAT GOLUBSKO-DOBRZYŃSKI',
        'POWIAT GOŁDAPSKI',
        'POWIAT GORLICKI',
        'POWIAT GORZOWSKI',
        'POWIAT GORZÓW WIELKOPOLSKI',
        'POWIAT GOSTYNIŃSKI',
        'POWIAT GOSTYŃSKI',
        'POWIAT GÓROWSKI',
        'POWIAT GRAJEWSKI',
        'POWIAT GRODZISKI',
        'POWIAT GRÓJECKI',
        'POWIAT GRUDZIĄDZ',
        'POWIAT GRUDZIĄDZKI',
        'POWIAT GRYFICKI',
        'POWIAT GRYFIŃSKI',
        'POWIAT HAJNOWSKI',
        'POWIAT HRUBIESZOWSKI',
        'POWIAT IŁAWSKI',
        'POWIAT INOWROCŁAWSKI',
        'POWIAT JANOWSKI',
        'POWIAT JAROCIŃSKI',
        'POWIAT JAROSŁAWSKI',
        'POWIAT JASIELSKI',
        'POWIAT JASTRZĘBIE-ZDRÓJ',
        'POWIAT JAWORSKI',
        'POWIAT JAWORZNO',
        'POWIAT JELENIA GÓRA',
        'POWIAT JELENIOGÓRSKI',
        'POWIAT JĘDRZEJOWSKI',
        'POWIAT KALISKI',
        'POWIAT KALISZ',
        'POWIAT KAMIENNOGÓRSKI',
        'POWIAT KAMIEŃSKI',
        'POWIAT KARTUSKI',
        'POWIAT KATOWICE',
        'POWIAT KAZIMIERSKI',
        'POWIAT KĘDZIERZYŃSKO-KOZIELSKI',
        'POWIAT KĘPIŃSKI',
        'POWIAT KĘTRZYŃSKI',
        'POWIAT KIELCE',
        'POWIAT KIELECKI',
        'POWIAT KLUCZBORSKI',
        'POWIAT KŁOBUCKI',
        'POWIAT KŁODZKI',
        'POWIAT KOLBUSZOWSKI',
        'POWIAT KOLNEŃSKI',
        'POWIAT KOLSKI',
        'POWIAT KOŁOBRZESKI',
        'POWIAT KONECKI',
        'POWIAT KONIN',
        'POWIAT KONIŃSKI',
        'POWIAT KOSZALIN',
        'POWIAT KOSZALIŃSKI',
        'POWIAT KOŚCIAŃSKI',
        'POWIAT KOŚCIERSKI',
        'POWIAT KOZIENICKI',
        'POWIAT KRAKOWSKI',
        'POWIAT KRAKÓW',
        'POWIAT KRAPKOWICKI',
        'POWIAT KRASNOSTAWSKI',
        'POWIAT KRAŚNICKI',
        'POWIAT KROSNO',
        'POWIAT KROŚNIEŃSKI',
        'POWIAT KROTOSZYŃSKI',
        'POWIAT KUTNOWSKI',
        'POWIAT KWIDZYŃSKI',
        'POWIAT LEGIONOWSKI',
        'POWIAT LEGNICA',
        'POWIAT LEGNICKI',
        'POWIAT LESKI',
        'POWIAT LESZCZYŃSKI',
        'POWIAT LESZNO',
        'POWIAT LEŻAJSKI',
        'POWIAT LĘBORSKI',
        'POWIAT LIDZBARSKI',
        'POWIAT LIMANOWSKI',
        'POWIAT LIPNOWSKI',
        'POWIAT LIPSKI',
        'POWIAT LUBACZOWSKI',
        'POWIAT LUBAŃSKI',
        'POWIAT LUBARTOWSKI',
        'POWIAT LUBELSKI',
        'POWIAT LUBIŃSKI',
        'POWIAT LUBLIN',
        'POWIAT LUBLINIECKI',
        'POWIAT LWÓWECKI',
        'POWIAT ŁAŃCUCKI',
        'POWIAT ŁASKI',
        'POWIAT ŁĘCZYCKI',
        'POWIAT ŁĘCZYŃSKI',
        'POWIAT ŁOBESKI',
        'POWIAT ŁOMŻA',
        'POWIAT ŁOMŻYŃSKI',
        'POWIAT ŁOSICKI',
        'POWIAT ŁOWICKI',
        'POWIAT ŁÓDZKI WSCHODNI',
        'POWIAT ŁÓDŹ',
        'POWIAT ŁUKOWSKI',
        'POWIAT MAKOWSKI',
        'POWIAT MALBORSKI',
        'POWIAT MIECHOWSKI',
        'POWIAT MIELECKI',
        'POWIAT MIĘDZYCHODZKI',
        'POWIAT MIĘDZYRZECKI',
        'POWIAT MIKOŁOWSKI',
        'POWIAT MILICKI',
        'POWIAT MIŃSKI',
        'POWIAT MŁAWSKI',
        'POWIAT MOGILEŃSKI',
        'POWIAT MONIECKI',
        'POWIAT MRĄGOWSKI',
        'POWIAT MYSŁOWICE',
        'POWIAT MYSZKOWSKI',
        'POWIAT MYŚLENICKI',
        'POWIAT MYŚLIBORSKI',
        'POWIAT NAKIELSKI',
        'POWIAT NAMYSŁOWSKI',
        'POWIAT NIDZICKI',
        'POWIAT NIŻAŃSKI',
        'POWIAT NOWODWORSKI',
        'POWIAT NOWOMIEJSKI',
        'POWIAT NOWOSĄDECKI',
        'POWIAT NOWOSOLSKI',
        'POWIAT NOWOTARSKI',
        'POWIAT NOWOTOMYSKI',
        'POWIAT NOWY SĄCZ',
        'POWIAT NYSKI',
        'POWIAT OBORNICKI',
        'POWIAT OLECKI',
        'POWIAT OLESKI',
        'POWIAT OLEŚNICKI',
        'POWIAT OLKUSKI',
        'POWIAT OLSZTYN',
        'POWIAT OLSZTYŃSKI',
        'POWIAT OŁAWSKI',
        'POWIAT OPATOWSKI',
        'POWIAT OPOCZYŃSKI',
        'POWIAT OPOLE',
        'POWIAT OPOLSKI',
        'POWIAT OSTROŁĘCKI',
        'POWIAT OSTROŁĘKA',
        'POWIAT OSTROWIECKI',
        'POWIAT OSTROWSKI',
        'POWIAT OSTRÓDZKI',
        'POWIAT OSTRZESZOWSKI',
        'POWIAT OŚWIĘCIMSKI',
        'POWIAT OTWOCKI',
        'POWIAT PABIANICKI',
        'POWIAT PAJĘCZAŃSKI',
        'POWIAT PARCZEWSKI',
        'POWIAT PIASECZYŃSKI',
        'POWIAT PIEKARY ŚLĄSKIE',
        'POWIAT PILSKI',
        'POWIAT PIŃCZOWSKI',
        'POWIAT PIOTRKOWSKI',
        'POWIAT PIOTRKÓW TRYBUNALSKI',
        'POWIAT PISKI',
        'POWIAT PLESZEWSKI',
        'POWIAT PŁOCK',
        'POWIAT PŁOCKI',
        'POWIAT PŁOŃSKI',
        'POWIAT PODDĘBICKI',
        'POWIAT POLICKI',
        'POWIAT POLKOWICKI',
        'POWIAT POZNAŃ',
        'POWIAT POZNAŃSKI',
        'POWIAT PROSZOWICKI',
        'POWIAT PRUDNICKI',
        'POWIAT PRUSZKOWSKI',
        'POWIAT PRZASNYSKI',
        'POWIAT PRZEMYSKI',
        'POWIAT PRZEMYŚL',
        'POWIAT PRZEWORSKI',
        'POWIAT PRZYSUSKI',
        'POWIAT PSZCZYŃSKI',
        'POWIAT PUCKI',
        'POWIAT PUŁAWSKI',
        'POWIAT PUŁTUSKI',
        'POWIAT PYRZYCKI',
        'POWIAT RACIBORSKI',
        'POWIAT RADOM',
        'POWIAT RADOMSKI',
        'POWIAT RADOMSZCZAŃSKI',
        'POWIAT RADZIEJOWSKI',
        'POWIAT RADZYŃSKI',
        'POWIAT RAWICKI',
        'POWIAT RAWSKI',
        'POWIAT ROPCZYCKO-SĘDZISZOWSKI',
        'POWIAT RUDA ŚLĄSKA',
        'POWIAT RYBNICKI',
        'POWIAT RYBNIK',
        'POWIAT RYCKI',
        'POWIAT RYPIŃSKI',
        'POWIAT RZESZOWSKI',
        'POWIAT RZESZÓW',
        'POWIAT SANDOMIERSKI',
        'POWIAT SANOCKI',
        'POWIAT SEJNEŃSKI',
        'POWIAT SĘPOLEŃSKI',
        'POWIAT SIEDLCE',
        'POWIAT SIEDLECKI',
        'POWIAT SIEMIANOWICE ŚLĄSKIE',
        'POWIAT SIEMIATYCKI',
        'POWIAT SIERADZKI',
        'POWIAT SIERPECKI',
        'POWIAT SKARŻYSKI',
        'POWIAT SKIERNIEWICE',
        'POWIAT SKIERNIEWICKI',
        'POWIAT SŁAWIEŃSKI',
        'POWIAT SŁUBICKI',
        'POWIAT SŁUPECKI',
        'POWIAT SŁUPSK',
        'POWIAT SŁUPSKI',
        'POWIAT SOCHACZEWSKI',
        'POWIAT SOKOŁOWSKI',
        'POWIAT SOKÓLSKI',
        'POWIAT SOPOT',
        'POWIAT SOSNOWIEC',
        'POWIAT STALOWOWOLSKI',
        'POWIAT STARACHOWICKI',
        'POWIAT STARGARDZKI',
        'POWIAT STAROGARDZKI',
        'POWIAT STASZOWSKI',
        'POWIAT STRZELECKI',
        'POWIAT STRZELECKO-DREZDENECKI',
        'POWIAT STRZELIŃSKI',
        'POWIAT STRZYŻOWSKI',
        'POWIAT SULĘCIŃSKI',
        'POWIAT SUSKI',
        'POWIAT SUWALSKI',
        'POWIAT SUWAŁKI',
        'POWIAT SZAMOTULSKI',
        'POWIAT SZCZECIN',
        'POWIAT SZCZECINECKI',
        'POWIAT SZCZYCIEŃSKI',
        'POWIAT SZTUMSKI',
        'POWIAT SZYDŁOWIECKI',
        'POWIAT ŚREDZKI',
        'POWIAT ŚREMSKI',
        'POWIAT ŚWIDNICKI',
        'POWIAT ŚWIDWIŃSKI',
        'POWIAT ŚWIEBODZIŃSKI',
        'POWIAT ŚWIECKI',
        'POWIAT ŚWIĘTOCHŁOWICE',
        'POWIAT ŚWINOUJŚCIE',
        'POWIAT TARNOBRZEG',
        'POWIAT TARNOBRZESKI',
        'POWIAT TARNOGÓRSKI',
        'POWIAT TARNOWSKI',
        'POWIAT TARNÓW',
        'POWIAT TATRZAŃSKI',
        'POWIAT TCZEWSKI',
        'POWIAT TOMASZOWSKI',
        'POWIAT TORUŃ',
        'POWIAT TORUŃSKI',
        'POWIAT TRZEBNICKI',
        'POWIAT TUCHOLSKI',
        'POWIAT TURECKI',
        'POWIAT TYCHY',
        'POWIAT WADOWICKI',
        'POWIAT WAŁBRZYCH',
        'POWIAT WAŁBRZYSKI',
        'POWIAT WAŁECKI',
        'POWIAT WARSZAWA',
        'POWIAT WARSZAWSKI ZACHODNI',
        'POWIAT WĄBRZESKI',
        'POWIAT WĄGROWIECKI',
        'POWIAT WEJHEROWSKI',
        'POWIAT WĘGORZEWSKI',
        'POWIAT WĘGROWSKI',
        'POWIAT WIELICKI',
        'POWIAT WIELUŃSKI',
        'POWIAT WIERUSZOWSKI',
        'POWIAT WŁOCŁAWEK',
        'POWIAT WŁOCŁAWSKI',
        'POWIAT WŁODAWSKI',
        'POWIAT WŁOSZCZOWSKI',
        'POWIAT WODZISŁAWSKI',
        'POWIAT WOLSZTYŃSKI',
        'POWIAT WOŁOMIŃSKI',
        'POWIAT WOŁOWSKI',
        'POWIAT WROCŁAW',
        'POWIAT WROCŁAWSKI',
        'POWIAT WRZESIŃSKI',
        'POWIAT WSCHOWSKI',
        'POWIAT WYSOKOMAZOWIECKI',
        'POWIAT WYSZKOWSKI',
        'POWIAT ZABRZE',
        'POWIAT ZAMBROWSKI',
        'POWIAT ZAMOJSKI',
        'POWIAT ZAMOŚĆ',
        'POWIAT ZAWIERCIAŃSKI',
        'POWIAT ZĄBKOWICKI',
        'POWIAT ZDUŃSKOWOLSKI',
        'POWIAT ZGIERSKI',
        'POWIAT ZGORZELECKI',
        'POWIAT ZIELONA GÓRA',
        'POWIAT ZIELONOGÓRSKI',
        'POWIAT ZŁOTORYJSKI',
        'POWIAT ZŁOTOWSKI',
        'POWIAT ZWOLEŃSKI',
        'POWIAT ŻAGAŃSKI',
        'POWIAT ŻARSKI',
        'POWIAT ŻNIŃSKI',
        'POWIAT ŻORY',
        'POWIAT ŻUROMIŃSKI',
        'POWIAT ŻYRARDOWSKI',
        'POWIAT ŻYWIECKI',
    ];

    private $accidentsFilter;

    public function __construct(array $accidentsFilter)
    {
        $this->accidentsFilter = $accidentsFilter;
    }

    public function getAccidentsFilterSql(): string
    {
        if (!empty($this->accidentsFilter)) {
            $query = implode(' AND ', $this->accidentsFilter);
        } else {
            $query = '';
        }
        $query = preg_replace(array('/\s{2,}/', '/[\t\n]/'), ' ', $query); //delete multiple spaces, newlines, etc.
        $query = trim($query);

        return $query;
    }
}