index:
    path: /
    controller: Sewik\Infrastructure\Controller\DefaultController::index

contact_page:
    path: /contact
    controller: Sewik\Infrastructure\Controller\DefaultController::contactPage

search:
    path: /search
    controller: Sewik\Infrastructure\Controller\DefaultController::searchPage

accident_page:
    path: /accident/{id}
    controller: Sewik\Infrastructure\Controller\DefaultController::showAccident

report_page:
    path: /report/{id}
    controller: Sewik\Infrastructure\Controller\DefaultController::singleReportPage

dashboard:
    path: /admin
    controller: Sewik\Infrastructure\Controller\AdminController::dashboard

create_template:
    path: /admin/createTemplate
    controller: Sewik\Infrastructure\Controller\AdminController::createTemplate

edit_template:
    path: /admin/editTemplate/{id}
    controller: Sewik\Infrastructure\Controller\AdminController::editTemplate
