index:
    path: /
    controller: App\Controller\DefaultController::index

search:
    path: /search
    controller: App\Controller\DefaultController::searchPage

accident_page:
    path: /accident/{id}
    controller: App\Controller\DefaultController::showAccident

dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard

create_template:
    path: /admin/createTemplate
    controller: App\Controller\AdminController::createTemplate

edit_template:
    path: /admin/editTemplate/{id}
    controller: App\Controller\AdminController::editTemplate
