index:
    path: /
    controller: App\Controller\DefaultController::index

reports:
    path: /reports
    controller: App\Controller\DefaultController::showFilteredReports

accident_list:
    path: /accidentList
    controller: App\Controller\DefaultController::accidentList

dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard

create_template:
    path: /admin/createTemplate
    controller: App\Controller\AdminController::createTemplate

edit_template:
    path: /admin/editTemplate/{id}
    controller: App\Controller\AdminController::editTemplate
