parameters:
    locale: 'pl'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Sewik\:
    resource: '../src/'
    exclude:
      - '../src/Application/Response/'
      - '../src/Application/Request/'
      - '../src/Domain/Dto/'
      - '../src/Domain/Entity/'
      - '../src/Domain/Exception/'
      - '../src/Infrastructure/Entity/'
      - '../src/Infrastructure/FieldType/'
      - '../src/Infrastructure/FormType/'
      - '../src/Kernel.php'

  Sewik\Infrastructure\Controller\:
    resource: '../src/Infrastructure/Controller'
    tags:
      - 'controller.service_arguments'
    calls:
      - [ setContainer, [ "@service_container" ] ]

  Sewik\Infrastructure\MysqlDatabase:
    arguments:
      - '%env(DATABASE_HOST)%'
      - '%env(DATABASE_USERNAME)%'
      - '%env(DATABASE_PASSWORD)%'
      - '%env(DATABASE_SCHEMA)%'

  Sewik\Infrastructure\MysqlAccidentsRepository:
    arguments:
      - '%env(DATABASE_HOST)%'
      - '%env(DATABASE_USERNAME)%'
      - '%env(DATABASE_PASSWORD)%'
      - '%env(DATABASE_SCHEMA)%'

  Sewik\Infrastructure\CachedDatabase:
    arguments:
      - '@Sewik\Infrastructure\DoctrineQueryResultCache'
      - '@Sewik\Infrastructure\MysqlDatabase'

# interfaces
  Sewik\Domain\DatabaseInterface: '@Sewik\Infrastructure\CachedDatabase'
  Sewik\Domain\TemplateRepositoryInterface: '@Sewik\Infrastructure\DoctrineTemplateRepository'
