services:
  _defaults:
    autowire: false      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true       # Allows optimizing the container by removing unused services; this also means

  sewik.database:
    class: Sewik\Infrastructure\MysqlDatabase
    arguments:
      - 'localhost'
      - 'root'
      - 'dupa.8'
      - 'sewik'

  sewik.report_cache:
    class: Sewik\Infrastructure\DoctrineReportCache
    arguments:
      - "@doctrine.orm.default_entity_manager"

  sewik.cached_database:
    class: Sewik\Infrastructure\CachedDatabase
    arguments:
      - '@sewik.report_cache'
      - '@sewik.database'

  sewik.template_repository:
    class: Sewik\Infrastructure\HardcodedTemplateRepository

  sewik.query_factory:
    class: Sewik\Domain\QueryFactory

  sewik.filter_factory:
    class: Sewik\Domain\FilterFactory

  sewik.service:
    class: Sewik\Domain\SewikService
    arguments:
      - '@sewik.cached_database'
      - '@sewik.template_repository'
      - '@sewik.query_factory'
      - '@sewik.filter_factory'