Sewik\Domain\Entity\QueryTemplate:
  type: entity
  table: query_templates
  id:
    id:
      type: uuid
      generator: { strategy: NONE }

  fields:
    name:
      type: string
    sqlQuery:
      type: text
    category:
      type: string
