Sewik\Infrastructure\Entity\CachedQueryResult:
  type: entity
  table: cached_query_results
  id:
    queryHash:
      type: string
      length: 40
      generator: { strategy: NONE }

  fields:
    queryResult:
      type: queryResultType
